### ISSUE TITLE
Guest user cannot shutdown the personal laptop

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#102]

**Comment by juhaerk** [comment]
Fixed in this commit: https://github.com/opinsys/puavo-ltsp/commit/fb28c09230dd2cad22736b9a51232f1e9c5af202. Note that this does have side effects: now guest logins work more correctly, thus, for example, nm-applet will show up on guest logins. This is not wanted behaviour at least on webkiosk mode.
