### ISSUE TITLE
Network manager indicator missing from personal laptop login screen

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#110]

**Comment by juhaerk** [comment]
Fixed in these commits: https://github.com/opinsys/opinsys-debs/commit/1f2472d83455d154917cfe76146b5ad2328e5e35, https://github.com/opinsys/opinsys-debs/commit/30880f0b2fe199b6f1385ceec8b4da422f45bc35, https://github.com/opinsys/opinsys-debs/commit/63f530f166a6ec3354cb2650e283c8646afff8b4.

Basically the problem was that we had dropped one patch in indicator-applet, hoping that it was useless with update to Trusty. It was not, it was needed so that indicator applets worked properly without their menus disappearing. Also, network-manager should use indicator-applet so that it shows up in login screen.
