### ISSUE TITLE
Ekapeli problems

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#116]
Ekapeli is quite problematic in a large netboot device environment. 
- It wants to download a lot of data to the users home directory which is very slow and takes a lot of space
- All the users have to do the downloading separately
- It has to be started from a website

We have a permission from the Ekapeli development team to include needed parts from the game to our image. Perhaps we could try to fix the situation in a following way
- Add game.jnlp to the device image
- Dedicate a folder from the "shared directories" for the game (directory with read/write rights, but not execute) 
- point the following environment variable to the shared directory according the users school (or maybe this could be stored in the same place at every bootserver) EKAPELI_CACHE_PATH=
- Fix the webmenu menu.json

**Comment by juhaerk** [comment]
Done in recent commits to ltsp-build, opinsys-debs and webmenu.

We setup the game data in "ekapeli"-package to /opt/ekapeli, and have some wrapper scripts to use fuse-mounts (with user rights) so setup the game data so that there is a cow/unionfs-mount where the game data resides (and user can write there).

It's a bit tricky, but appears to work okay (for now).
