### ISSUE TITLE
Pulse audio creates a new configuration file on every login

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#131]
This takes a lot of inodes and doesn't sound like a too smart  way to behave.

**Comment by juhaerk** [comment]
Pulseaudio tries to lookup /etc/machine-id, and as it is missing in our system, it uses /var/lib/dbus/machine-id, that is set up by ltsp init-scripts (50-machine-id more exactly). This should be unique for each machine and persistent across boots. As thin and fat clients do not have persistent storage, we need to generate machine-id that should remain constant for each machine, yet also be unique (no two machines should share the same machine-id).

I would like the machine-id be an identifier which could also be used to look up the host, thus machine-id is generated from host mac-address.

Fixed in commit: https://github.com/opinsys/puavo-ltsp/commit/06b3983e70c996a0507c5de536a3d67396295397
