### ISSUE TITLE
Second display blanks out on login

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#144]
During login some teacher workstations loose the picture on the other display (video projector). Only way to fix the issue is to reboot.

lspci

```
[] adm-asokero@jaho-416-ope:~$ lspci
00:00.0 Host bridge: Intel Corporation 2nd Generation Core Processor Family DRAM Controller (rev 09)
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
00:16.0 Communication controller: Intel Corporation 6 Series/C200 Series Chipset Family MEI Controller #1 (rev 04)
00:16.3 Serial controller: Intel Corporation 6 Series/C200 Series Chipset Family KT Controller (rev 04)
00:19.0 Ethernet controller: Intel Corporation 82579LM Gigabit Network Connection (rev 04)
00:1a.0 USB controller: Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #2 (rev 04)
00:1c.0 PCI bridge: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 1 (rev b4)
00:1c.4 PCI bridge: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 5 (rev b4)
00:1c.6 PCI bridge: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 7 (rev b4)
00:1c.7 PCI bridge: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 8 (rev b4)
00:1d.0 USB controller: Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #1 (rev 04)
00:1e.0 PCI bridge: Intel Corporation 82801 PCI Bridge (rev a4)
00:1f.0 ISA bridge: Intel Corporation Q65 Express Chipset Family LPC Controller (rev 04)
00:1f.2 SATA controller: Intel Corporation 6 Series/C200 Series Chipset Family SATA AHCI Controller (rev 04)
00:1f.3 SMBus: Intel Corporation 6 Series/C200 Series Chipset Family SMBus Controller (rev 04)
```

Device outputs:
- Displayport -> video projector using Display Port to VGA-adapter
- VGA > Monitor

I cannot reproduce the problem using a Device with similar chipset.

Could be related to this: https://bugs.freedesktop.org/show_bug.cgi?id=84038

**Comment by juhaerk** [comment]
The xrandr-plugin in gnome-settings-daemon is misbehaving with some hardware combinations. It may not find another screen or may continuously keep changing the resolution of some display. Especially some setups with video projectors and/or document cameras may be prone to this.

I am guessing that running xrandr on those displays will trigger "display has been attached" message that the gnome-settings-daemon will react to and then run xrandr again.

I do not know any other solution to the problem except disabling the xrandr-plugin in gnome-settings-daemon. We have a special device tag for this: "force_puavo_xrandr", that will force the xrandr settings in Puavo in effect (turning off the xrandr-plugin).

The unfortunate side effect of this is that users can not change display setups themselves (when "force_puavo_xrandr" is set). Displays can be configured to the desired setup from Puavo xrandr-commands, though. However, because of this, it is inadvisable to use the "force_puavo_xrandr" unless there is a real need due to misbehaving gnome-settings-daemon.
