### ISSUE TITLE
Add support for X2go-server on ltsp-servers

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#16]

**Comment by juhaerk** [comment]
x2go packages (x2goclient + x2goserver) are in the device image, so that is okay.

However, x2go can not be used with Gnome, unless gnome-session is fixed/updated. See https://bugs.launchpad.net/ubuntu/+source/gnome-session/+bug/1251281. Packages in ppa:eugenesan/ppa can be used to fix the issue (this is Trusty-specific, though).

**Comment by juhaerk** [comment]
This might be relevant: https://bugzilla.gnome.org/show_bug.cgi?id=731173#c4.

**Comment by juhaerk** [comment]
Fixed in commit: https://github.com/opinsys/opinsys-debs/commit/18959dcc3b5ce603bae7cf9fd031184b4dc87238 (thanks, Eugene!)
