### ISSUE TITLE
External usb-mouse stops working on laptop

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#178]
Using external usb mouse on a laptop is not possible. This is propably due to some powersaving feature. If laptop has an external usb mouse and power source connected mouse works fine. If power source is disconnected the mouse will be powered off after a few seconds.

**Comment by tuomasjjrasanen** [comment]
Confirmed.

**Comment by tuomasjjrasanen** [comment]
These might be related:
http://askubuntu.com/questions/141832/usb-mouse-sleeping-after-5-seconds-when-on-battery
http://askubuntu.com/questions/80638/how-to-disable-auto-power-off-of-usb-devices-like-usb-mouse
http://ubuntuforums.org/showthread.php?t=1954215

**Comment by tuomasjjrasanen** [comment]
Hmm.. it might be that the mouse does not support USB autosuspend properly. I can see three options: either we
1) collect usb ids of those broken devices and blacklist autosuspend for them, this option might be quite difficult in practice, but it allows properly functional devices to save power
2) blacklist a whole usb driver, usbhid for example
3) disable the usb autosuspend completely

I'd like to go with Option#1, but I recognize that it might be really difficult if not impossible task. I tested with three different USB mice and one keyboard. None of the mice woke up, the keyboard worked properly though.

Option#3 would probably be overkill. So I think I'm going with Option#2. It is suboptimal, but better than disabling the autosuspend completely. Since the bug is reportedly affecting external USB mice, Option#2 should fix it.

**Comment by tuomasjjrasanen** [comment]
Done: https://github.com/opinsys/puavo-rules/commit/31bbc56bb252d1d63a312a6ba410dfec368cc04b
