### ISSUE TITLE
Notify users about updated system

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#180]
Currently we have link to change log at the webmenu. Still users cannot know when updates have been made and will be unaware about the made fixes and new features. We need a notifier to indicate about made changes and important information.

**Comment by juhaerk** [comment]
Solved mostly in this merge commit: https://github.com/opinsys/opinsys/commit/d775adebb124d009b0d328941e089e7803970122

Note that that is in the private Opinsys-repository for now. That is because the Opinsys-image changelog is Opinsys-specific stuff. We might open that up once we figure out how to make that useful in a public setting (perhaps once we have open source images available?).
