### ISSUE TITLE
Automatically reboot zombie netboot devices

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#186]
Rebooting bootservers usually results netboot devices such as fatclients or thin client servers to end up as living dead with squashfs error on screen.

Would it be possible to indentify these situations at the client and automatically reboot the devices?

**Comment by juhaerk** [comment]
Something like this might do (but I do think that the `has_nbd_connection()` should be more robust):

```
#!/bin/sh

has_nbd_connection() {
  [ "$(pgrep -c nbd-client)" -eq 2 ]
}

while has_nbd_connection; do
  sleep 30
done

echo b > /proc/sysrq-trigger
```

Even better would be if we could recover from nbd failures without a reboot.

**Comment by juhaerk** [comment]
Some kind of a solution to this has been made in these commits: https://github.com/opinsys/puavo-ltsp/commit/f5caf43e3867388e30a539f6e0585cb0ff4c1472 and https://github.com/opinsys/puavo-ltsp/commit/0dd9b58dda8580a51d5f70a89f853d14e2730798.

These do a reboot if nbd connection has been broken at some point, and once the nbd-server is up and accepting connections. It will wait for a maximum of eight hours + some little time, and then will reboot anyway (poweroff might be a better option though). Rebooting anyway might be a reasonable thing to do in case the test for nbd-server availability is broken for some reason. The test is not used at all if it is considered it is likely not functional, instead an immediate reboot is done.

Some adjustments to the above heuristics might be in place. Perhaps reboots should not be done if the test is not functional, and perhaps there should not be any timeout.

A better solution would be to fix nbd. nbd-client does have the -persist option which should restart the connection. This, however, does not work from the initial nbd-client process (which is started from the ramdisk). Apparently it has two root directories (?!?), on 0:1 and 0:18 devices, and when reconnecting it also re-opens the nbd-device, but it is not available on the filesystem that it sees. It also looks up things under /sys, but these do not exist under the root directory that it sees.

If nbd-client is detached/killed and restarted (with -persist), then it has only one root directory and it should work correctly, even the -persist option. The problem with -persist, however, is that when the connection it broken for some time, it returns I/O error to applications, and they may crash. The effect may be that the system may go and remain into an unusable state despite the nbd-connection coming up again. The only safe way to be sure appears to do a reboot.

Another option is using nbd-proxy, which appears to work as desired. It can be turned on by using "NBDCLIENT=nbd-client-proxy" kernel argument. When nbd-connection is broken, it will try to establish it again and does not return I/O error to applications, instead it lets them wait. This appears to be what we want. However, our experiences on nbd-proxy on year 2010 were that it was very unreliable on some networks. Thus careful testing is needed before it is put widely into production.

I am not yet closing this ticket because I feel that the heuristics on the current version need some rethinking.

**Comment by juhaerk** [comment]
I simplified the logic on when reboots should happen: https://github.com/opinsys/puavo-ltsp/commit/b3ee7d3c24495311bf7b67900af568c862c86b91. Closing.
