### ISSUE TITLE
Add Globilab to restricted device image

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#197]
http://www.globisens.net/support#2

We have asked a permission to distribute and use the software with all our own customers. We could add the package to the restricted device image and also make a launcher for it to the webmenu.

**Comment by juhaerk** [comment]
Done. We took away the postinst-script in the upstream deb-package, because it does ugly things. Tested with a customer who appears to be satisfied with the result.

The relevant commits: https://github.com/opinsys/opinsys-debs/commit/ea8649ed2e5f5bca690eff5f8703d2321bff00e7, https://github.com/opinsys/opinsys-debs/commit/f5b83765dc1d9c9494430f455169e152e0897659 and https://github.com/opinsys/opinsys-debs/commit/a3a6b0605980b8fa117f4e273e85cbe25e69b201.
