### ISSUE TITLE
Add VidyoDesktop client to device image

### ISSUE THREAD

**Issue by cjoohs** [opinsys/puavo#214]
http://vportal1.videovisit.mobi/upload/VidyoDesktopInstaller-ubuntu-TAG_VD_3_3_0_027.deb
http://vportal1.videovisit.mobi/upload/VidyoDesktopInstaller-ubuntu64-TAG_VD_3_3_0_027.deb

**Comment by juhaerk** [comment]
This software has a handicapped license, it can be read like this:

```
wget -q -O - http://vportal1.videovisit.mobi/upload/VidyoDesktopInstaller-ubuntu-TAG_VD_3_3_0_027.deb \
  | dpkg-deb --fsys-tarfile /dev/stdin \
  | tar -x --to-stdout ./opt/vidyo/VidyoDesktop/license.txt \
  | fmt \
  | less
```

I am not putting this in before someone else looks at that in more detail.

Note that license text contains the following passage:

```
Accordingly, except as otherwise expressly provided under this Agreement, Customer
shall have no right and Customer specifically agrees not to: ... make error corrections to or
otherwise modify or adapt the Product, Software or create derivative works based upon the
Software, or permit third parties to do the same.
```

We cannot ship it quite as it is, because it contains an obnoxious autostart that starts it up for all users (and, because it marks the fact that user has accepted EULA outside home directories (and thus that is non-persistent on our systems), it requests users to accept EULA every time after a host has rebooted). On the other hand the autostart file is a configuration file, so is changing that a a Product modification? (I am understanding it is.)

I also do not find a permission to re-distribute, quite the opposite.

I have not been able to test it properly (I do not have access into any VidyoPortal), but after very short testing I got it into a busy loop and it was blocking logout for... maybe a minute?

puavo-pkg for selected users might be a solution?  Is this worth that?

**Comment by juhaerk** [comment]
We have a clarification on (private) email, that says this should be okay...

I will look at what needs to be done technically, minimally.

**Comment by juhaerk** [comment]
Done. Apparently on thin clients only audio-mode is supported (Direct Rending is not detected). On fat clients and laptops it should be okay.

Still waiting for the legal advice...

**Comment by juhaerk** [comment]
See commit https://github.com/opinsys/opinsys/blob/master/rules/puppet/vidyodesktop/manifests/init.pp if your permissions allow.
