### ISSUE TITLE
Suspend not reliable on HP probook G2

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#223]

**Comment by juhaerk** [comment]
There are two kinds of issues: one is that after suspend the internal monitor may be blank. The other is that the machine may spontaneously suspend, especially on events relating to network or video.

We are testing if a bios update solves these issues.

**Comment by juhaerk** [comment]
We found out the common cause of both issues. It actually does not have anything to do with software.

It turns out that when two HP Probook 430 G2 (or G1) are stacked on top of each other, the computer on the top may "think" that its lid is closed even when it is not. Now the screen will blank, and if the computer is configured to suspend when its lid is closed, it will also suspend. It can be resumed, but the display will continue to be blank if the computer "thinks" its lid is closed.

The problem can be reproduced with a small magnet, from below the machine/keyboard.

Spent many hours chasing this mysterious bug! The shielding should be better on these models.
