### ISSUE TITLE
Cleaning persistent OverlayFS after image update

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#229]
After image update user could be offered a possibility to clean the persistent overlayfs information concerning images that don't exist anymore.

**Comment by juhaerk** [comment]
I have implemented similar idea in a rather different way: overlays can be deleted by primary user in development mode, with the applet that is normally used to do image/puavo-pkg updates (system update functionality is disabled in development mode).

Deleting overlays in normal mode with image updates does not make so much sense, because overlays are not used or available in normal mode.

Relevant commits: https://github.com/opinsys/puavo-ltsp/commit/2ef2ec097eb49ebb0bbfc4d9c6cf1119d6ede2df and https://github.com/opinsys/puavo-ltsp/commit/e91b81497b3d2eb855dc6f028272afc2c5ca6581.
