### ISSUE TITLE
Fix missing icons from the Webmenu on trusty device image

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#26]
- Accessories > Printers
- Graphics > Kolourpaint
- Graphics > Pinta
- Learning > Tuxmath
- Sound & video > Solfege
- Sound & video > Hydrogen
- Sound & video > fmit

**Comment by juhaerk** [comment]
There is a bug in webmenu on this line: https://github.com/opinsys/webmenu/blob/master/src/menutools.coffee#L18

The problem is that all types of images should be accepted by webmenu (well, all types it can support), not just png images.

Perhaps epeli would like to fix that so I do not have to dig my hands to javascript this time ;-)

**Comment by juhaerk** [comment]
This is otherwise done (thanks Esa-Matti!), but xpm-icons are apparently not supported, I would guess because the webkit does not support those.
