### ISSUE TITLE
Update certificates automatically at wireless access points and ltspservers when needed

### ISSUE THREAD

**Issue by cjoohs** [opinsys/puavo#290]
puavo-update-certificate or similar operations should be run automatically at wireless access points and ltspservers to update certificates needed by puavo-vpn-client.

Same is done for laptops, so this should be quite easy to do.

**Comment by tuomasjjrasanen** [comment]
wirelessaccesspoints were already updating their certificates automatically, just like laptops, because they use the same update mechanism. However, because ltspserver's are netboot devices, they did not run the same update and config procedure as laptops and wirelessaccesspoints.

On ltspservers, puavo-update-certificate is now cronified and this issue should be fixed.

See https://github.com/opinsys/puavo-ltsp/commit/e0ddcd1e95eac1b4f7197dd5ec4b628686928732
