### ISSUE TITLE
Fix NFS

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#41]
NFS has serious stability issues on Puavo netboot devices causing kernel call traces and panics.

**Comment by juhaerk** [comment]
Use a kernel from Ubuntu Precise! 3.2.x series rules! If your hardware supports it and apps too, it is okay with Ubuntu Trusty!

**Comment by juhaerk** [comment]
I am closing this because nobody is doing anything to this and we are mostly satisfied with the current situation. We may have to revisit this when we need to update ltsp-servers to version greater than 3.2.x. Besides, "Fix NFS" is too generic a ticket, we can never close this if we need to make it perfect.
