### ISSUE TITLE
Remove shutdown etc. options when in webkiosk-mode

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#46]
In webkiok-mode the following options should be removed from the Webmenu logout screen:
- reboot
- shutdown
- hibernate
- suspend

**Comment by juhaerk** [comment]
I did an ugly hack regarding this: https://github.com/opinsys/puavo-ltsp/commit/53215cb8e7fb90b76f5d1187f2278836089d0581

It basically just breaks the functionality so that reboot/shutdown does not work. Hibernate and suspend does not show up in the webmenu anyway. Reboot and shutdown should have the same treatment, now those are just buttons that do not work.

Note that none of this actually blocks users ability to do reboot/shutdown/hibernate/suspend. That is another matter.

Not closing, because webmenu still needs interface changes.

**Comment by juhaerk** [comment]
I fixed this nicely in webmenu: https://github.com/opinsys/webmenu/commit/bf430afdc023bc160f400f74a63b2bb4c0119f29, https://github.com/opinsys/puavo-ltsp/commit/014b1aec194076a812db80788dc536e783595e09, https://github.com/opinsys/ltsp-build/commit/c1c664fb8560d5cf8ca30f7fb2dbf071c455b578, removed the previous hack (only from Trusty, actually). Should work in Quantal and Trusty.
