### ISSUE TITLE
Libreoffice in Trusty has trouble opening Excel spreadsheets

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#49]
Opening excel (xls) spreadsheets with Ubuntu Trust Libreoffice 4.2.3.3. While opening the files Libreoffice tries to import them as text-files. Example files to reproduce the problen can be found for example just by googling " xls example file".

**Comment by asokero** [comment]
It seems like this issue is not reproducable on a standard Ubuntu Trusty desktop installation. In that case the problem might be caused by some of the hacks made to the libreoffice at image build.

**Comment by juhaerk** [comment]
The issue does not exist if libreoffice hacks were not applied during the image build.

**Comment by juhaerk** [comment]
Fixed by not trying to set the default formats. The file formats have changed to the extent that setting the default file formats appears tricky, and the files from Quantal were not compatible with new Libreoffice.

Closing. A new ticket should be opened, if the default file formats still need to be set.
