### ISSUE TITLE
Logging in as a "new user" always asks for entering a gnomekeyring password

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#56]
This could be repeated with the device image ltsp-trusty-trusty-2014-05-19-11919 on a laptop installation.

**Comment by asokero** [comment]
This is problematic to basic user because they might not understand what this keyring thing means. Still it can be useful for advanced user who then again can make use of it from the accessories.

**Comment by juhaerk** [comment]
Fixed with this commit: https://github.com/opinsys/ltsp-build/commit/2fece3bee517fa23717f0398236a4e14061f1f2a.  I decided to simple turn the gnome-keyring-daemon autostart off, and unfortunately it required tricks in two different places (with dpkg-divert), in /etc/xdg/autostart and /usr/share/dbus-1/services. There is a kind of gnome-keyring autostart in pam as well, but that does not seem to affect it (it is for password integration, and perhaps could be disabled there are well).

The package is still there and hopefully still useful for some. (We'll see what it takes for those who need the gnome-keyring).
