### ISSUE TITLE
Fix puavo-wlanap on trusty device image

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#6]

**Comment by juhaerk** [comment]
puavo-wlanap did not work with the hostapd- and vtun-versions that were in Trusty. With vtun there were some issues relating to authentication (vtun version on bootserver was 3.0.2-4build1 and on Trusty there was 3.0.3-2). The standard Ubuntu Trusty hostapd could not create the wlan*_0 interfaces (or some other problem prevented it from going further). Hostapd on Trusty was version 1:2.1-0ubuntu1, we are now using 1:2.0-1 with some patches.

This issue was solved by porting the versions for vtun and hostapd that were used with Quantal to Trusty.
