### ISSUE TITLE
Ktouch & step applications won´t run from webmenu

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#61]
They can be executed from the terminal but not from webmenu.

**Comment by juhaerk** [comment]
The list that I found was: kturtle, kwordquiz, ktouch, step, okular and tellico. I helped webmenu a bit with those: https://github.com/opinsys/webmenu/commit/716d37c86a4da4b62ff03bbf64463c9fbfd4a18c.

(There is a better way to fix this by teaching webmenu about the specifics of Exec-line syntax. However, solving this particular problem by adding "command"-attributes is easy and similar problems have been fixed in the same way before).
