### ISSUE TITLE
Setting xrandr from puavo does not seem to work

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#66]
Setting xrandr lines to a client device from Puavo does not seem to do anything anymore.

**Comment by juhaerk** [comment]
The problem was that gnome-settings-daemon interferes right after xrandr changes by puavo-ltsp-client has been made, and changes settings back to what it considers right.

gnome-settings-daemon reads /etc/gnome-settings-daemon/xrandr/monitors.xml and applies changes there, so that could be used for effect perhaps. But it does change settings even if that file does not exist.

This issue was fixed by telling gnome-settings-daemon that the xrandr plugin should not be active:
https://github.com/opinsys/ltsp-build/commit/0b0bcddfeda4f0650eb231c36d91e6ac4615151f.
