### ISSUE TITLE
Setting graphics driver for laptop

### ISSUE THREAD

**Issue by asokero** [opinsys/puavo#75]
Setting the graphics driver for a laptop does not seem to work for a laptop.

**Comment by juhaerk** [comment]
The real problem was that puavo-rest produces syntactically faulty lts.conf, with PUAVO_TAGS not set to any string. Thus the XSERVER setting could not go through.

This was fixed by not fixing the lts.conf generation (we are going to do away with that anyway), but by setting XSERVER directly from /etc/puavo/device.json. The configuration mechanism for XSERVER is still the one used in ltsp.

Fixed in these commits: https://github.com/opinsys/puavo-ltsp/commit/6c4288d35dbc760624aebc506d182f5d33d8de22 and https://github.com/opinsys/puavo-ltsp/commit/9333e02bba1dae676767e7f4d1f1ff6744b33bb5.
