### ISSUE TITLE
Easier login for primary users

### ISSUE THREAD

**Issue by vmlintu** [opinsys/puavo#90]
If user has been set as the primary user for a device in Puavo, the user should be shown as a selection button on lightdm login screen and asked only the password. This can be useful on personal laptops and teacher desktops that are primarily used by the same user. Other users should still be able to login to the device by typing in their username and password.

**Comment by juhaerk** [comment]
Fixed by these commits: https://github.com/opinsys/puavo-ltsp/commit/3fe4e5189b7e3c4b44a2d7f9164efdccd49f0502, https://github.com/opinsys/puavo-ltsp/commit/0a4bd26f2aaf613e26d91ab885613cebfe4e9ffd and https://github.com/opinsys/unity-greeter/commit/d7382d2e3bab51fbc269695f8a2abe2ade962cd4, https://github.com/opinsys/unity-greeter/commit/cadd81773b86404e723ad314fcd05f748a19c1ae.
